language: node

node_js:
  - 'stable'

cache:
  directories:
    - node_modules

script:
  - yarn
  - yarn fix
  - yarn test:cov
  - yarn build

branches:
  only:
    - master

notifications:
  email: false
