language: node

node_js:
  - 12

cache:
  directories:
    - node_modules

script:
  - yarn
  - yarn fix
  - yarn test:cov
  - yarn build

branches:
  only:
    - master
    - staging

notifications:
  email: false
